[phases.build]
cmds = ['mvn clean package -DskipTests']
cacheDirectories = ['/app/.m2']

[phases.setup]
nixPkgs = ['openjdk17', 'maven']

[start]
cmd = 'java -jar target/shift-manager-0.0.1-SNAPSHOT.jar'

[variables]
MAVEN_OPTS = '-Xmx1024m'
NIXPACKS_DOWNLOAD_BUFFER_SIZE = '52428800'